# Generated by Django 5.2.5 on 2025-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
