# Generated by Django 5.2.5 on 2025-09-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('sessao', 'Sessão'), ('avaliacao', 'Avaliação'), ('seguimento', 'Seguimento'), ('outro', 'Outro')], max_length=50)),
                ('data', models.DateField()),
                ('duracao', models.DurationField()),
                ('terapeuta', models.CharField(max_length=100)),
                ('paciente', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True, null=True)),
                ('presenca_confirmada', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuario.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('psicologo', 'Psicólogo(a)'), ('medico', 'Médico(a)'), ('terapeuta_ocupacional', 'Terapeuta Ocupacional'), ('fisioterapeuta', 'Fisioterapeuta'), ('nutricionista', 'Nutricionista'), ('fonoaudiologo', 'Fonoaudiólogo(a)'), ('outros', 'Outros')], max_length=50)),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='terapias.clinica')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('data_termino', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='usuario.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='RotinaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('periodicidade', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('pontual', 'Pontual')], max_length=50)),
                ('dias_semana', models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=50, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao', models.DurationField()),
                ('descricao', models.TextField()),
                ('horario', models.TimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='terapias.rotina')),
            ],
        ),
    ]
