# Generated by Django 5.2.5 on 2025-09-03 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='terapeuta',
        ),
        migrations.AddField(
            model_name='evento',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='terapias.clinica'),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='terapias.profissional'),
        ),
        migrations.AddField(
            model_name='rotinaitem',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotinas_itens', to='terapias.clinica'),
        ),
        migrations.AddField(
            model_name='rotinaitem',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotinas_itens', to='terapias.profissional'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='criado_por',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='criado_por',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='terapias.clinica'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='criado_por',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='criado_por',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rotinaitem',
            name='criado_por',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rotinaitem',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinaitem',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinaitem',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinaitem',
            name='rotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas_itens', to='terapias.rotina'),
        ),
    ]
