# Generated by Django 5.2.5 on 2025-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0002_remove_evento_paciente_remove_evento_terapeuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotina',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
