# Generated by Django 5.2.5 on 2025-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0003_alter_rotina_data_termino_alter_rotina_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotinaitem',
            name='horario',
        ),
        migrations.AlterField(
            model_name='rotinaitem',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
