# Generated by Django 5.2.5 on 2025-09-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0004_remove_rotinaitem_horario_alter_rotinaitem_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data',
            new_name='data_evento',
        ),
    ]
