# Generated by Django 5.2.5 on 2025-09-04 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0005_rename_data_evento_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
