# Generated by Django 5.2.5 on 2025-09-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0006_rotina_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='origem_rotina_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_gerados', to='terapias.rotinaitem'),
        ),
    ]
